### ISSUE TITLE
Clean UP & Dockerization of eos7pw8

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos7pw8#4] opened 2023-06-01 09:12 UTC
Hi @samuelmaina !

Please check the repo is up to date with the newest workflows and structure

**Comment by samuelmaina** [comment] 2023-06-05 04:19
@GemmaTuron , I have created a new PR. Can I choose another model and self assign from the project list models for cleaning?

**Comment by GemmaTuron** [comment] 2023-06-07 17:08
Hi @samuelmaina 

The DockerHub build has failed. Please check the action to understand what might have happened

**Comment by samuelmaina** [comment] 2023-06-08 10:16
@GemmaTuron the model failed due to the arm64 (specifically, modules are not installed, rdkit was not found) build but AMD was successful. The resolution of the Arm64 issue in the template I think will solve this issue for the model.

**Comment by GemmaTuron** [comment] 2023-06-08 10:25
Hi @samuelmaina 

Please work together with @ZakiaYahya and @emmakodes to understand how can we bypass this issue on the ARM64 build. Are all models failing due to RDKIT?

**Comment by GemmaTuron** [comment] 2023-06-09 07:22
Hi @samuelmaina 

Can you check the RDKIT issue and see if another rdkit version would be able to build the ARM64?

**Comment by samuelmaina** [comment] 2023-06-09 08:13
@GemmaTuron Different models are failing due to different packages. Let me see if we would be able to run the docker.yaml locally and I will see if a different rdkit version will run.

**Comment by GemmaTuron** [comment] 2023-06-16 07:00
Hi @samuelmaina 

What is the progress here?

**Comment by samuelmaina** [comment] 2023-06-16 07:25
@GemmaTuron , thanks for the reminder.I  will try the suggested rdkit versions.

**Comment by GemmaTuron** [comment] 2023-06-19 06:38
Hi @samuelmaina 
I don't see any PR, you mention in this [issue](https://github.com/ersilia-os/eos526j/issues/1) you did the changes?

**Comment by samuelmaina** [comment] 2023-06-19 07:15
@GemmaTuron , the last PR was using rdkit 2023.3.1  so I thought Emma issue may have caused the docker to fail. You can run the PR manually and tell if it still fails.

**Comment by GemmaTuron** [comment] 2023-06-19 11:39
the Action is running, please check it when its ready

**Comment by samuelmaina** [comment] 2023-06-19 11:59
Still failed. I am seeing the latest version of  rdkit should work with the ARM64 and that is what I have done, (I haven't put the rdkit specific version).Let me continue to investigate the issue further

**Comment by samuelmaina** [comment] 2023-06-19 13:53
@GemmaTuron , I have made a PR. Conda was resovling to the rdkit 2020.03.  even if I was giving the latest version. I have set and confirmed  that it always resolves to 2023.03 version. I have opened a  PR, can you merge it to see if it will succeed?

**Comment by miquelduranfrigola** [comment] 2023-06-20 16:40
@GemmaTuron - once you have merged the PR, we can update the workflows of this model. Let me know if you need my help.

**Comment by GemmaTuron** [comment] 2023-06-21 06:15
@samuelmaina 
You are installing rdkit twice. I have modified the Dockerfile to save time and added the new workflows. Please next time make sure to check for this :
```
RUN pip install rdkit==2023.03.1
RUN conda install -c rdkit -c lich syba
```

**Comment by GemmaTuron** [comment] 2023-06-21 06:17
The new workflows are running, let us know the outcome @samuelmaina !

**Comment by samuelmaina** [comment] 2023-06-21 06:26
> @samuelmaina You are installing rdkit twice. I have modified the Dockerfile to save time and added the new workflows. Please next time make sure to check for this :
> 
> ```
> RUN pip install rdkit==2023.03.1
> RUN conda install -c rdkit -c lich syba
> ```
Sorry for the misunderstanding.The first command is installing rdkit but the second is sourcing syba from the the lich channel which is found in the rdkit channel. The syba package must be fetched from the the two nested channels. syba comes with rdkit 2020 but with the two commands it resolves to 2023 version.

**Comment by GemmaTuron** [comment] 2023-06-21 06:27
Ok, so syba need the 2020 version but having the 2023 works?

**Comment by samuelmaina** [comment] 2023-06-21 06:32
> fetched



> Ok, so syba need the 2020 version but having the 2023 works?

Yes @GemmaTuron . I was able to predict with it and checked the model env and it was resolving to 2023

**Comment by GemmaTuron** [comment] 2023-06-21 07:38
@samuelmaina 

I've catched a bug in th workflow files thanks to the runs in this repo, check this [issue](https://github.com/ersilia-os/eos-template/issues/29)
I'll now update the dockerfile again to the rdkit channel and  please check that the workflows complete successfully

**Comment by samuelmaina** [comment] 2023-06-21 08:27
@GemmaTuron , I think the logic of the issue is good, it will work . The syba fails for ARM 64.  syba is a native package written by the model authors. I don't know how we can solve this but I will try.

**Comment by samuelmaina** [comment] 2023-06-21 08:28
But the docker workflow registers success since AMD version was correctly built

**Comment by GemmaTuron** [comment] 2023-07-13 14:34
@samuelmaina 
The latest build on docker is failing, could you check? If we are unable to build the docker image with the zip file we might want to revert to the previous version of the model... @miquelduranfrigola what do you think?

**Comment by GemmaTuron** [comment] 2023-07-13 14:35
I see this error, the syba package seems to not be able to be installed:
`#5 154.7 Model API eos7pw8:run did not produce an outputError occurred while loading the model: No module named 'syba'
`

**Comment by samuelmaina** [comment] 2023-07-14 10:36
@GemmaTuron , The model was only building for AMD 64 but now builds for both architectures and the image sizes of the two are also equal and greatly minimized. Maybe you can investigate this to see if the  same can done to  produce the ARM 64 images and also reduce the Docker image size.

**Comment by samuelmaina** [comment] 2023-07-14 10:37
@GemmaTuron , The model was only building for AMD 64 but now builds for both architectures and the image sizes of the two are also equal and greatly minimized. Maybe you can investigate this to see if the  same can done to  produce the ARM 64 images  for other models and also reduce the Docker image size.

**Comment by samuelmaina** [comment] 2023-07-14 10:37
Hi @GemmaTuron , 
The model was only building for AMD 64 but now builds for both architectures and the image sizes of the two are also equal and greatly minimized. Maybe you can investigate this to see if the  same can done to  produce the ARM 64 images  for other models and also reduce the Docker image size.

**Comment by GemmaTuron** [comment] 2023-07-14 13:25
Hi @samuelmaina 
this can be done in the case where a package has been uploaded in the internet, in this case Syba is a conda package so we can wget it. Is not always the case and not always convenient, but we can keep this in mind for future use cases, of course!

**Closed as completed** 2023-08-08 11:36 UTC
